# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[es]
  languageCode = "es-ar"
  contentDir = "content/es"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a third language.
[pt]
  languageCode = "pt-br"
  contentDir = "content/pt"
  title = "MicroSudAqua"
  [pt.params]
    description = "Rede Colaborativa em Ecologia Microbiana Aquática da América Latina"
 # [[pt.menu.main]]
 #   name = "Início"
 #   url = "#home"
 #   weight = 10
    
[[pt.menu.main]]
  name = "Início"
  weight = 10
  identifier = "home"

[[pt.menu.main]]
  name = "Apresentação"
  url = "#home"
  weight = 10
  parent = "home"
  
[[pt.menu.main]]
  name = "Objetivos"
  url = "#aims"
  weight = 10
  parent = "home"

[[pt.menu.main]]
  name = "Grupos de Estudo"
  weight = 20
  identifier = "groups"

[[pt.menu.main]]
  name = "Observatorio"
  url = "#observatory"
  weight = 20
  parent = "groups"
  
[[pt.menu.main]]
  name = "Estequimetria"
  url = "#stoichiometry"
  weight = 20
  parent = "groups"
  
[[pt.menu.main]]
  name = "Traços"
  url = "#traits"
  weight = 20
  parent = "groups"

[[pt.menu.main]]
  name = "Padrões"
  url = "#patterns"
  weight = 20
  parent = "groups"
 
[[pt.menu.main]]
  name = "Contato"
  url = "#contact"
  weight = 30
  
[[pt.menu.main]]
  name = "Pessoal"
  weight = 40
  identifier = "people"
  
[[pt.menu.main]]
  name = "Nós"
  url = "#people"
  weight = 40
  parent = "people"
  
[[pt.menu.main]]
  name = "Participantes"
  url = "#participant"
  weight = 40
  parent = "people"
  
[[pt.menu.main]]
  name = "Eventos"
  url = "#events"
  weight = 50
    
[[pt.menu.main]]
  name = "Produção"
  url = " "
  weight = 60
  identifier = "pub"

[[pt.menu.main]]
  name = "Publicações"
  url = "#publications"
  weight = 60
  parent = "pub"

[[pt.menu.main]]
  name = "Protocolos"
  url = " "
  weight = 60
  parent = "pub"

[[pt.menu.main]]
  name = "Scripts"
  url = "https://github.com/microsudaqua"
  weight = 60
  parent = "pub"
  
[[pt.menu.main]]
  name = "Database"
  url = "https://www.ncbi.nlm.nih.gov/"
  weight = 70

# Uncomment the lines below to configure your website in a second language.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "MicroSudAqua"
  [en.params]
    description = "Latin American Collaborative Network in Aquatic Microbial Ecology"
#[[en.menu.main]]
#    name = "Início"
#    url = "#home"
#    weight = 10

[[en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"

[[en.menu.main]]
  name = "Presentation"
  url = "#home"
  weight = 10
  parent = "home"
  
[[en.menu.main]]
  name = "Aims"
  url = "#aims"
  weight = 10
  parent = "home"

[[en.menu.main]]
  name = "Study Groups"
  weight = 20
  identifier = "groups"

[[en.menu.main]]
  name = "Observatory"
  url = "#observatory"
  weight = 20
  parent = "groups"
  
[[en.menu.main]]
  name = "Stoichiometry"
  url = "#stoichiometry"
  weight = 20
  parent = "groups"
  
[[en.menu.main]]
  name = "Traits"
  url = "#traits"
  weight = 20
  parent = "groups"

[[en.menu.main]]
  name = "Patterns"
  url = "#patterns"
  weight = 20
  parent = "groups"
 
[[en.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 30
  
[[en.menu.main]]
  name = "People"
  weight = 40
  identifier = "people"
  
[[en.menu.main]]
  name = "Nodes"
  url = "#people"
  weight = 40
  parent = "people"
  
[[en.menu.main]]
  name = "Participants"
  url = "#participant"
  weight = 40
  parent = "people"
  
[[en.menu.main]]
  name = "Events"
  url = "#events"
  weight = 50
    
[[en.menu.main]]
  name = "Production"
  url = " "
  weight = 60
  identifier = "pub"

[[en.menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 60
  parent = "pub"

[[en.menu.main]]
  name = "Protocols"
  url = " "
  weight = 60
  parent = "pub"

[[en.menu.main]]
  name = "Scripts"
  url = "https://github.com/microsudaqua"
  weight = 60
  parent = "pub"
  
[[en.menu.main]]
  name = "Database"
  url = "https://www.ncbi.nlm.nih.gov/"
  weight = 70



