# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[es]
  languageCode = "es-ar"
  contentDir = "content/es"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a third language.
[pt]
  languageCode = "pt-br"
  contentDir = "content/pt"
  title = "µSudAqua"
  [pt.params]
    description = "Rede Colaborativa em Ecologia Microbiana Aquática da América Latina"
 # [[pt.menu.main]]
 #   name = "Início"
 #   url = "#home"
 #   weight = 10
    
[[pt.menu.main]]
  name = "Início"
  weight = 10
  identifier = "home"

[[pt.menu.main]]
  name = "Apresentação"
  url = "#home"
  weight = 11
  parent = "home"
  
[[pt.menu.main]]
  name = "Objetivos"
  url = "#aims"
  weight = 12
  parent = "home"

[[pt.menu.main]]
  name = "Grupos de Estudo"
  url = "groups/"
  weight = 20
  identifier = "groups"

[[pt.menu.main]]
  name = "Observatórios"
  url = "groups/#observatory"
  weight = 21
  parent = "groups"
  
[[pt.menu.main]]
  name = "Estequimetria"
  url = "groups/#stoichiometry"
  weight = 22
  parent = "groups"
  
[[pt.menu.main]]
  name = "Traços"
  url = "groups/#traits"
  weight = 23
  parent = "groups"

[[pt.menu.main]]
  name = "Padrões"
  url = "groups/#patterns"
  weight = 24
  parent = "groups"

[[pt.menu.main]]
  name = "Inicio de Carreira"
  url = "groups/#picosudaqua"
  weight = 25
  parent = "groups"
 
[[pt.menu.main]]
  name = "Contato"
  weight = 30
  identifier = "contato"

[[pt.menu.main]]
  name = "E-mail"
  url = "#contact"
  weight = 31
  parent = "contato"

[[pt.menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com/microsudaqua/"
  weight = 32
  parent = "contato"

[[pt.menu.main]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UC9fbpMSqVo-ev5npXWlmkRQ"
  weight = 33
  parent = "contato"
  
[[pt.menu.main]]
  name = "Pessoal"
  weight = 40
  identifier = "people"
  
[[pt.menu.main]]
  name = "Nós"
  url = "#people"
  weight = 41
  parent = "people"
  
[[pt.menu.main]]
  name = "Participantes"
  url = "#participant"
  weight = 42
  parent = "people"
  
[[pt.menu.main]]
  name = "Eventos"
  url = "events/events"
  weight = 50
    
[[pt.menu.main]]
  name = "Produção"
  url = " "
  weight = 60
  identifier = "pub"

[[pt.menu.main]]
  name = "Publicações"
  url = "#publications"
  weight = 61
  parent = "pub"

[[pt.menu.main]]
  name = "Protocolos"
  url = " "
  weight = 62
  parent = "pub"

[[pt.menu.main]]
  name = "Scripts"
  url = "https://github.com/microsudaqua"
  weight = 63
  parent = "pub"
  
[[pt.menu.main]]
  name = "Database"
  url = "#database"
  weight = 64
  parent = "pub"

[[pt.menu.main]]
  name = "Oportunidades de financiamento"
  url = "https://docs.google.com/spreadsheets/d/1gR2lXpfa63DL88pfsaHFULMNj_-XlEG7NuT1i1NmWbM/edit?usp=sharing"
  weight = 70
  identifier = "opo"

# Uncomment the lines below to configure your website in a second language.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "µSudAqua"
  [en.params]
    description = "Latin American Collaborative Network in Aquatic Microbial Ecology"
#[[en.menu.main]]
#    name = "Início"
#    url = "#home"
#    weight = 10

[[en.menu.main]]
  name = "Home"
  weight = 11
  identifier = "home"

[[en.menu.main]]
  name = "Presentation"
  url = "#home"
  weight = 12
  parent = "home"
  
[[en.menu.main]]
  name = "Aims"
  url = "#aims"
  weight = 13
  parent = "home"

[[en.menu.main]]
  name = "Study Groups"
  url = "groups/"
  weight = 20
  identifier = "groups"

[[en.menu.main]]
  name = "Observatory"
  url = "groups/#observatory"
  weight = 21
  parent = "groups"
  
[[en.menu.main]]
  name = "Stoichiometry"
  url = "groups/#stoichiometry"
  weight = 22
  parent = "groups"
  
[[en.menu.main]]
  name = "Traits"
  url = "groups/#traits"
  weight = 23
  parent = "groups"

[[en.menu.main]]
  name = "Patterns"
  url = "groups/#patterns"
  weight = 24
  parent = "groups"

[[en.menu.main]]
  name = "Early carreer"
  url = "groups/#picosudaqua"
  weight = 25
  parent = "groups"
 
[[en.menu.main]]
  name = "Contact"
  weight = 30
  identifier = "contact"

[[en.menu.main]]
  name = "E-mail"
  url = "#contact"
  weight = 31
  parent = "contact"

[[en.menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com/microsudaqua/"
  weight = 32
  parent = "contact"

[[en.menu.main]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UC9fbpMSqVo-ev5npXWlmkRQ"
  weight = 33
  parent = "contact"
  
[[en.menu.main]]
  name = "People"
  weight = 40
  identifier = "people"
  
[[en.menu.main]]
  name = "Nodes"
  url = "#people"
  weight = 41
  parent = "people"
  
[[en.menu.main]]
  name = "Participants"
  url = "#participant"
  weight = 42
  parent = "people"
  
[[en.menu.main]]
  name = "Events"
  url = "events/events"
  weight = 50
    
[[en.menu.main]]
  name = "Production"
  url = " "
  weight = 60
  identifier = "pub"

[[en.menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 61
  parent = "pub"

[[en.menu.main]]
  name = "Protocols"
  url = " "
  weight = 62
  parent = "pub"

[[en.menu.main]]
  name = "Scripts"
  url = "https://github.com/microsudaqua"
  weight = 63
  parent = "pub"
  
[[en.menu.main]]
  name = "Database"
  url = "#database"
  weight = 64
  parent = "pub"

[[en.menu.main]]
  name = "Funding opportunities"
  url = "https://docs.google.com/spreadsheets/d/1gR2lXpfa63DL88pfsaHFULMNj_-XlEG7NuT1i1NmWbM/edit?usp=sharing"
  weight = 70
  identifier = "opo"


