# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 10
  identifier = "home"

[[main]]
  name = "Presentation"
  url = "#home"
  weight = 10
  parent = "home"
  
[[main]]
  name = "Aims"
  url = "#aims"
  weight = 10
  parent = "home"

[[main]]
  name = "Events"
  #url = " "
  weight = 10
  parent = "home"

[[main]]
  name = "Study Goups"
  weight = 20
  identifier = "groups"

[[main]]
  name = "Observatory"
  #url = "#home"
  weight = 20
  parent = "groups"
  
[[main]]
  name = "Stoichiometry"
  #url = "#home"
  weight = 20
  parent = "groups"
  
[[main]]
  name = "Traits"
  #url = "#home"
  weight = 20
  parent = "groups"
 
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 30
  
[[main]]
  name = "People"
  weight = 40
  identifier = "people"
  
[[main]]
  name = "Nodes"
  url = "#people"
  weight = 40
  parent = "people"
  
[[main]]
  name = "Participants"
  #url = "#home"
  weight = 40
  parent = "people"
  
[[main]]
  name = "Publications"
  url = "#featured"
  weight = 50
  
[[main]]
  name = "Database"
  #url = " "
  weight = 60

##############################################################
#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 50
#
#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 60
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
