# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 10
  identifier = "home"

[[main]]
  name = "Presentación"
  url = "#home"
  weight = 10
  parent = "home"
  
[[main]]
  name = "Objetivos"
  url = "#aims"
  weight = 10
  parent = "home"

[[main]]
  name = "Grupos de Estudio"
  weight = 20
  identifier = "groups"

[[main]]
  name = "Observatorio"
  url = "#observatory"
  weight = 20
  parent = "groups"
  
[[main]]
  name = "Estequimetría"
  url = "#stoichiometry"
  weight = 20
  parent = "groups"
  
[[main]]
  name = "Rasgos"
  url = "#traits"
  weight = 20
  parent = "groups"
 
[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 30
  
[[main]]
  name = "Personas"
  weight = 40
  identifier = "people"
  
[[main]]
  name = "Nodos"
  url = "#nodes"
  weight = 40
  parent = "people"
  
[[main]]
  name = "Participantes"
  url = "#participant"
  weight = 40
  parent = "people"
  
[[main]]
  name = "Eventos"
  #url = "#events"
  weight = 50
    
[[main]]
  name = "Producción"
  url = " "
  weight = 60
  identifier = "pub"

[[main]]
  name = "Publicaciones"
  url = "#publications"
  weight = 60
  parent = "pub"

[[main]]
  name = "Protocolos"
  url = " "
  weight = 60
  parent = "pub"

[[main]]
  name = "Scripts"
  url = "https://github.com/microsudaqua"
  weight = 60
  parent = "pub"
  
[[main]]
  name = "Database"
  url = "https://www.ncbi.nlm.nih.gov/"
  weight = 70

##############################################################
#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 50
#
#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 60
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
